### ISSUE TITLE
Timecycle modifier

### ISSUE THREAD

**Issue by ivegotthis** [BerkieBb/bMenu#6]
Hi, In the vMenu you can save your personnel settings but it didn't save the timecycle modifier option, be great if you could with this and also WTF! the Vmenu had like 791 visuals options yours has nearly 3000, it going to take me ages to find the perfect one :)

**Comment by BerkieBb** [comment]
Saving settings will come soon, I have a to-do list written [here](https://github.com/BerkieBb/bMenu/blob/main/client/main.lua#L181-L203) so you can see what I have to do and contribute to that list as well. Also, I strive to generate as much options from the game as possible instead of hardcoding it to avoid it getting outdated quickly and needing a lot of manual updates.

**Comment by BerkieBb** [comment]
Either way, I'm glad to see you like it so far.

**Comment by ivegotthis** [comment]
It's great, A new version has been needed for so long as the vMenu can use half a ms when open, yours I don't even see on the top half of the resources window.
